In [1]:
from tensorflow.keras.layers import Input, MaxPooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = MaxPooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 2, 2, 3)          0         
 )                                                               
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = np.random.randint(-127, 127, (1,5,5,3))
X

array([[[[ -17,   98,  -17],
         [-122, -101,   75],
         [  62,    0,   58],
         [ -76,   16,   88],
         [ -43,  -40,   67]],

        [[ -29,   96,   90],
         [ -64,   -9,  -16],
         [  10,   37,  -77],
         [ -72,   91,    6],
         [  84,  -47, -119]],

        [[ -30,   48,  -48],
         [-113,  -72,   73],
         [ -34,   96,   62],
         [ -18,   85,    0],
         [  -5,   77,  -16]],

        [[ -87,  -70,  -49],
         [ -80,   22,  -35],
         [ 117,  -20,   41],
         [ -18,  -70,   91],
         [  -7,   77,  -53]],

        [[ -19,   35,   75],
         [-120,  107,   54],
         [  13,   71,   84],
         [ -49,  -46,   81],
         [  88,   81,  118]]]])

In [5]:
y = model.predict(X)
y

1/1 [==============================] - 0s 42ms/step


2022-12-09 00:42:59.470616: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[-17.,  98.,  90.],
         [ 62.,  91.,  88.]],

        [[-30.,  48.,  73.],
         [117.,  96.,  91.]]]], dtype=float32)

In [6]:
in_json = {
    "in": X.astype(int).flatten().tolist()
}

In [7]:
out_json = {
    "out": y.astype(int).flatten().tolist()
}

In [8]:
import json

In [9]:
with open("maxPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [10]:
with open("maxPooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [11]:
inputs = Input(shape=(10,10,3))
x = MaxPooling2D(pool_size=2, strides=3)(inputs)
model = Model(inputs, x)

In [12]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 3, 3, 3)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [13]:
X = np.random.randint(-127, 127, (1,10,10,3))
X

array([[[[  93,  -38,  -77],
         [ -50,    5,   26],
         [-108,    1, -109],
         [-110,   90,  -83],
         [  32,  -10,   67],
         [  49,  -26, -113],
         [ -26, -110,  100],
         [ -68,   33,  -43],
         [  16,   91,  -44],
         [ 119,   21,   33]],

        [[-112,   94,   -3],
         [  39,  -73,  125],
         [ -99,  -81,   64],
         [   1,   20,   44],
         [ -29,  -66, -127],
         [   7,  108,  -75],
         [-121,  -82,   80],
         [ -46,  -17,  -41],
         [ -86,  -44,  -76],
         [  21,  -88,   44]],

        [[-122, -118,   29],
         [   3,   80,  -76],
         [-101,  123,   16],
         [-121,  -40,   72],
         [ -55,   49,   28],
         [ -91,   39,   26],
         [  65,  -14,  -41],
         [ 104,  -70,  -10],
         [-105,  -44,  -78],
         [  48,  -26,   15]],

        [[  14,   -6,    1],
         [ -28,  122,    7],
         [  20,   74,   49],
         [ -24,  -82,   80],
        

In [14]:
y = model.predict(X)
y

1/1 [==============================] - 0s 20ms/step


array([[[[ 93.,  94., 125.],
         [ 32.,  90.,  67.],
         [-26.,  33., 100.]],

        [[ 42., 122.,   7.],
         [ 48., 125.,  80.],
         [125.,  48., 118.]],

        [[110., 121.,  58.],
         [ 18., 114.,  51.],
         [ 45.,  28., 110.]]]], dtype=float32)

In [15]:
in_json = {
    "in": X.astype(int).flatten().tolist()
}

In [16]:
out_json = {
    "out": y.astype(int).flatten().tolist()
}

In [17]:
with open("maxPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [18]:
with open("maxPooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f)