In [1]:
from tensorflow.keras.layers import Input, AveragePooling2D, Lambda
from tensorflow.keras import Model
import numpy as np

In [2]:
scale = 4

In [3]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
x = Lambda(lambda x: x*scale)(x)
model = Model(inputs, x)

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
average_pooling2d (AveragePo (None, 2, 2, 3)           0         
_________________________________________________________________
lambda (Lambda)              (None, 2, 2, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [5]:
X = np.random.randint(-127, 127, (1,5,5,3))
X

array([[[[  18,   47,    4],
         [ -47,  109,  -28],
         [  -9,  -68,   61],
         [ -79,    2,   35],
         [   1,   20,  111]],

        [[ -16,   -2,   10],
         [-118,  114,   47],
         [-111,   32,   81],
         [  23,  -77,   94],
         [ -53, -102,  -58]],

        [[  28,  -26,  -34],
         [ -62,  -23,  -16],
         [-127,   91,  -37],
         [  33,   31,   25],
         [ -42,  -13,    2]],

        [[ -56,    7,  -21],
         [  69,   21,   42],
         [  93,  -77,  -59],
         [  37,  -41,   46],
         [  -4,   -9,  -93]],

        [[  67,   73,  116],
         [  -3,  106,  -74],
         [ -17,  -74,  -28],
         [ -69,   98,   45],
         [-109,  -18,  -27]]]])

In [6]:
y = model.predict(X)
y

array([[[[-163.,  268.,   33.],
         [-176., -111.,  271.]],

        [[ -21.,  -21.,  -29.],
         [  36.,    4.,  -25.]]]], dtype=float32)

In [7]:
in_json = {
    "in": X.astype(int).flatten().tolist()
}

In [8]:
out_json = {
    "scale": scale,
    "out": y.astype(int).flatten().tolist()
}

In [9]:
import json

In [10]:
with open("sumPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("sumPooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [12]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=2, strides=3)(inputs)
x = Lambda(lambda x: x*scale)(x)
model = Model(inputs, x)

In [13]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 10, 3)]       0         
_________________________________________________________________
average_pooling2d_1 (Average (None, 3, 3, 3)           0         
_________________________________________________________________
lambda_1 (Lambda)            (None, 3, 3, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [14]:
X = np.random.randint(-127, 127, (1,10,10,3))
X

array([[[[   3,  100,   34],
         [  89,  -53,  -97],
         [  -5,   77,  112],
         [  24,   72,  -68],
         [   8, -117,   70],
         [ 112,  106, -124],
         [ 123,  -14,  -13],
         [ -99,  -53,   21],
         [ -69,  -27,   23],
         [  38,   93,  -65]],

        [[ -55,  -75,  -25],
         [  87,   34, -126],
         [ -79,  -62,  122],
         [ -35,   79,  -70],
         [ -19,  -29, -127],
         [  52,   12,  -62],
         [-111,   84,  -85],
         [  61,  120,   11],
         [  65,  -11,  -95],
         [ -30,   17,   18]],

        [[  33,   29,  -34],
         [ 114,   71,   49],
         [ -58,   90, -112],
         [  66,   51,  -99],
         [ -93,  122,  -80],
         [ -93,   50,   11],
         [-115,  -94,    9],
         [  22,   94, -104],
         [   1,  -94,   12],
         [ 108,  -12, -124]],

        [[-109,  -64,  -47],
         [ 124,  -39,  -46],
         [ -84,   55,   44],
         [  90,  107,   92],
        

In [15]:
y = model.predict(X)
y

array([[[[ 124.,    6., -214.],
         [ -22.,    5., -195.],
         [ -26.,  137.,  -66.]],

        [[ 120., -272.,    4.],
         [  10.,   55.,  -15.],
         [-363.,   45., -153.]],

        [[ -77.,   91., -120.],
         [  16.,  -28.,   10.],
         [-226.,   76.,   87.]]]], dtype=float32)

In [16]:
in_json = {
    "in": X.astype(int).flatten().tolist()
}

In [17]:
out_json = {
    "scale": scale,
    "out": y.astype(int).flatten().tolist()
}

In [18]:
with open("sumPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [19]:
with open("sumPooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f)